# -*- coding: utf-8 -*-
"""全量表模型（由 information_schema 自动生成）"""
from sqlalchemy import BigInteger, SmallInteger, Integer, Float, String, Text, DateTime, Date
from sqlalchemy.orm import Mapped, mapped_column
from .mixins import PkMixin


class AcceptanceRecord(PkMixin):
    __tablename__ = "acceptance_record"
    equip_name: Mapped[object] = mapped_column(String(400), comment="equip_name")
    equip_udi: Mapped[object] = mapped_column(String(100), comment="equip_udi")
    supplier: Mapped[object] = mapped_column(String(200), comment="supplier")
    person: Mapped[object] = mapped_column(String(100), comment="person")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    result: Mapped[object] = mapped_column(String(40), comment="result")
    issue: Mapped[object] = mapped_column(Text, comment="issue")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class AdverseEvent(PkMixin):
    __tablename__ = "adverse_event"
    equip_name: Mapped[object] = mapped_column(String(400), comment="equip_name")
    equip_udi: Mapped[object] = mapped_column(String(100), comment="equip_udi")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    desc: Mapped[object] = mapped_column(Text, comment="desc")
    severity: Mapped[object] = mapped_column(String(40), comment="severity")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    reporter: Mapped[object] = mapped_column(String(100), comment="reporter")
    report_date: Mapped[object] = mapped_column(DateTime, comment="report_date")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class ApprovalNotification(PkMixin):
    __tablename__ = "approval_notification"
    title: Mapped[object] = mapped_column(String(400), comment="title")
    content: Mapped[object] = mapped_column(Text, comment="content")
    module: Mapped[object] = mapped_column(String(100), comment="module")
    ref_no: Mapped[object] = mapped_column(String(100), comment="ref_no")
    ref_id: Mapped[object] = mapped_column(BigInteger, comment="ref_id")
    action_type: Mapped[object] = mapped_column(String(60), comment="action_type")
    target_role: Mapped[object] = mapped_column(String(100), comment="target_role")
    target_user: Mapped[object] = mapped_column(String(100), comment="target_user")
    source_user: Mapped[object] = mapped_column(String(100), comment="source_user")
    is_read: Mapped[object] = mapped_column(SmallInteger, comment="is_read")
    read_at: Mapped[object] = mapped_column(DateTime, comment="read_at")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class CalibrationPlan(PkMixin):
    __tablename__ = "calibration_plan"
    equip_name: Mapped[object] = mapped_column(String(400), comment="equip_name")
    equip_udi: Mapped[object] = mapped_column(String(100), comment="equip_udi")
    cal_no: Mapped[object] = mapped_column(String(100), comment="cal_no")
    last_cal: Mapped[object] = mapped_column(String(40), comment="last_cal")
    next_cal: Mapped[object] = mapped_column(String(40), comment="next_cal")
    org: Mapped[object] = mapped_column(String(200), comment="org")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class CalibrationRecord(PkMixin):
    __tablename__ = "calibration_record"
    equip_name: Mapped[object] = mapped_column(String(400), comment="equip_name")
    equip_udi: Mapped[object] = mapped_column(String(100), comment="equip_udi")
    cal_date: Mapped[object] = mapped_column(DateTime, comment="cal_date")
    result: Mapped[object] = mapped_column(String(40), comment="result")
    cert: Mapped[object] = mapped_column(String(100), comment="cert")
    org: Mapped[object] = mapped_column(String(200), comment="org")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class CertUpdateRequest(PkMixin):
    __tablename__ = "cert_update_request"
    module: Mapped[object] = mapped_column(String(60), comment="module")
    record_id: Mapped[object] = mapped_column(BigInteger, comment="record_id")
    record_name: Mapped[object] = mapped_column(String(500), comment="record_name")
    field_changes: Mapped[object] = mapped_column(Text, comment="field_changes")
    new_data: Mapped[object] = mapped_column(Text, comment="new_data")
    update_reason: Mapped[object] = mapped_column(Text, comment="update_reason")
    workflow_status: Mapped[object] = mapped_column(String(40), comment="workflow_status")
    submitted_by: Mapped[object] = mapped_column(String(100), comment="submitted_by")
    submitted_at: Mapped[object] = mapped_column(DateTime, comment="submitted_at")
    reviewed_by: Mapped[object] = mapped_column(String(100), comment="reviewed_by")
    reviewed_at: Mapped[object] = mapped_column(DateTime, comment="reviewed_at")
    review_opinion: Mapped[object] = mapped_column(Text, comment="review_opinion")
    approved_by: Mapped[object] = mapped_column(String(100), comment="approved_by")
    approved_at: Mapped[object] = mapped_column(DateTime, comment="approved_at")
    approval_opinion: Mapped[object] = mapped_column(Text, comment="approval_opinion")
    applied_at: Mapped[object] = mapped_column(DateTime, comment="applied_at")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class CureRecord(PkMixin):
    __tablename__ = "cure_record"
    equip_name: Mapped[object] = mapped_column(String(400), comment="equip_name")
    equip_udi: Mapped[object] = mapped_column(String(100), comment="equip_udi")
    type: Mapped[object] = mapped_column(String(100), comment="type")
    person: Mapped[object] = mapped_column(String(100), comment="person")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    temp: Mapped[object] = mapped_column(String(20), comment="temp")
    humid: Mapped[object] = mapped_column(String(20), comment="humid")
    result: Mapped[object] = mapped_column(String(40), comment="result")
    next_date: Mapped[object] = mapped_column(DateTime, comment="next_date")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class CustomerArchive(PkMixin):
    __tablename__ = "customer_archive"
    name: Mapped[object] = mapped_column(String(400), comment="name")
    code: Mapped[object] = mapped_column(String(100), comment="code")
    type: Mapped[object] = mapped_column(String(100), comment="type")
    license: Mapped[object] = mapped_column(String(200), comment="license")
    license_expire: Mapped[object] = mapped_column(String(40), comment="license_expire")
    contact: Mapped[object] = mapped_column(String(100), comment="contact")
    phone: Mapped[object] = mapped_column(String(60), comment="phone")
    address: Mapped[object] = mapped_column(String(500), comment="address")
    credit_level: Mapped[object] = mapped_column(String(40), comment="credit_level")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    audit_status: Mapped[object] = mapped_column(String(40), comment="audit_status")
    auditor: Mapped[object] = mapped_column(String(100), comment="auditor")
    audit_date: Mapped[object] = mapped_column(DateTime, comment="audit_date")
    audit_opinion: Mapped[object] = mapped_column(Text, comment="audit_opinion")
    workflow_status: Mapped[object] = mapped_column(String(40), comment="workflow_status")
    entered_by: Mapped[object] = mapped_column(String(100), comment="entered_by")
    entered_at: Mapped[object] = mapped_column(DateTime, comment="entered_at")
    reviewed_by: Mapped[object] = mapped_column(String(100), comment="reviewed_by")
    reviewed_at: Mapped[object] = mapped_column(DateTime, comment="reviewed_at")
    review_opinion: Mapped[object] = mapped_column(Text, comment="review_opinion")
    approved_by: Mapped[object] = mapped_column(String(100), comment="approved_by")
    approved_at: Mapped[object] = mapped_column(DateTime, comment="approved_at")
    approval_opinion: Mapped[object] = mapped_column(Text, comment="approval_opinion")
    cert_update_status: Mapped[object] = mapped_column(String(40), comment="cert_update_status")
    cert_update_id: Mapped[object] = mapped_column(BigInteger, comment="cert_update_id")
    cert_update_at: Mapped[object] = mapped_column(DateTime, comment="cert_update_at")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class DataBridgeLog(PkMixin):
    __tablename__ = "data_bridge_log"
    bridge_type: Mapped[object] = mapped_column(String(100), comment="bridge_type")
    source_module: Mapped[object] = mapped_column(String(100), comment="source_module")
    source_ref: Mapped[object] = mapped_column(String(200), comment="source_ref")
    target_module: Mapped[object] = mapped_column(String(100), comment="target_module")
    target_ref: Mapped[object] = mapped_column(String(200), comment="target_ref")
    description: Mapped[object] = mapped_column(Text, comment="description")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class EquipAcceptance(PkMixin):
    __tablename__ = "equip_acceptance"
    equip_udi: Mapped[object] = mapped_column(String(100), comment="equip_udi")
    equip_name: Mapped[object] = mapped_column(String(400), comment="equip_name")
    supplier: Mapped[object] = mapped_column(String(200), comment="supplier")
    customer_name: Mapped[object] = mapped_column(String(400), comment="customer_name")
    dept_name: Mapped[object] = mapped_column(String(200), comment="dept_name")
    serial_no: Mapped[object] = mapped_column(String(200), comment="serial_no")
    qty: Mapped[object] = mapped_column(BigInteger, comment="qty")
    use_years: Mapped[object] = mapped_column(String(100), comment="use_years")
    type: Mapped[object] = mapped_column(String(40), comment="type")
    person: Mapped[object] = mapped_column(String(100), comment="person")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    result: Mapped[object] = mapped_column(String(40), comment="result")
    step: Mapped[object] = mapped_column(String(40), comment="step")
    check_items: Mapped[object] = mapped_column(Text, comment="check_items")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class EquipInspection(PkMixin):
    __tablename__ = "equip_inspection"
    equip_name: Mapped[object] = mapped_column(String(400), comment="equip_name")
    equip_udi: Mapped[object] = mapped_column(String(100), comment="equip_udi")
    customer_name: Mapped[object] = mapped_column(String(400), comment="customer_name")
    dept_name: Mapped[object] = mapped_column(String(200), comment="dept_name")
    serial_no: Mapped[object] = mapped_column(String(200), comment="serial_no")
    type: Mapped[object] = mapped_column(String(40), comment="type")
    inspector: Mapped[object] = mapped_column(String(100), comment="inspector")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    result: Mapped[object] = mapped_column(String(40), comment="result")
    status_desc: Mapped[object] = mapped_column(Text, comment="status_desc")
    note: Mapped[object] = mapped_column(Text, comment="note")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class EquipLedger(PkMixin):
    __tablename__ = "equip_ledger"
    udi: Mapped[object] = mapped_column(String(100), comment="udi")
    name: Mapped[object] = mapped_column(String(200), comment="name")
    model: Mapped[object] = mapped_column(String(200), comment="model")
    cls: Mapped[object] = mapped_column(String(40), comment="cls")
    risk: Mapped[object] = mapped_column(String(40), comment="risk")
    cert: Mapped[object] = mapped_column(String(200), comment="cert")
    factory: Mapped[object] = mapped_column(String(200), comment="factory")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    customer_name: Mapped[object] = mapped_column(String(400), comment="customer_name")
    production_date: Mapped[object] = mapped_column(DateTime, comment="production_date")
    serial_no: Mapped[object] = mapped_column(String(200), comment="serial_no")
    qty: Mapped[object] = mapped_column(BigInteger, comment="qty")
    service_life: Mapped[object] = mapped_column(String(100), comment="service_life")
    sale_price: Mapped[object] = mapped_column(Float, comment="sale_price")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class ExpiryWarning(PkMixin):
    __tablename__ = "expiry_warning"
    udi: Mapped[object] = mapped_column(String(100), comment="udi")
    name: Mapped[object] = mapped_column(String(400), comment="name")
    batch: Mapped[object] = mapped_column(String(100), comment="batch")
    prod_date: Mapped[object] = mapped_column(DateTime, comment="prod_date")
    expire_date: Mapped[object] = mapped_column(DateTime, comment="expire_date")
    remain_days: Mapped[object] = mapped_column(BigInteger, comment="remain_days")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    manufacturer: Mapped[object] = mapped_column(String(400), comment="manufacturer")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class FinanceRecord(PkMixin):
    __tablename__ = "finance_record"
    category: Mapped[object] = mapped_column(String(40), comment="category")
    type: Mapped[object] = mapped_column(String(100), comment="type")
    amount: Mapped[object] = mapped_column(Float, comment="amount")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    ref_no: Mapped[object] = mapped_column(String(100), comment="ref_no")
    dept: Mapped[object] = mapped_column(String(200), comment="dept")
    operator: Mapped[object] = mapped_column(String(100), comment="operator")
    note: Mapped[object] = mapped_column(Text, comment="note")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class FirstFactoryAudit(PkMixin):
    __tablename__ = "first_factory_audit"
    name: Mapped[object] = mapped_column(String(400), comment="name")
    code: Mapped[object] = mapped_column(String(100), comment="code")
    type: Mapped[object] = mapped_column(String(100), comment="type")
    license: Mapped[object] = mapped_column(String(200), comment="license")
    license_expire: Mapped[object] = mapped_column(String(40), comment="license_expire")
    gmp_cert: Mapped[object] = mapped_column(String(200), comment="gmp_cert")
    gmp_expire: Mapped[object] = mapped_column(String(40), comment="gmp_expire")
    iso_cert: Mapped[object] = mapped_column(String(200), comment="iso_cert")
    iso_expire: Mapped[object] = mapped_column(String(40), comment="iso_expire")
    business_license: Mapped[object] = mapped_column(String(200), comment="business_license")
    scope: Mapped[object] = mapped_column(String(500), comment="scope")
    address: Mapped[object] = mapped_column(String(500), comment="address")
    legal_person: Mapped[object] = mapped_column(String(100), comment="legal_person")
    contact: Mapped[object] = mapped_column(String(100), comment="contact")
    phone: Mapped[object] = mapped_column(String(60), comment="phone")
    applicant: Mapped[object] = mapped_column(String(100), comment="applicant")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    first_reviewer: Mapped[object] = mapped_column(String(100), comment="first_reviewer")
    first_review_date: Mapped[object] = mapped_column(DateTime, comment="first_review_date")
    first_review_opinion: Mapped[object] = mapped_column(Text, comment="first_review_opinion")
    second_reviewer: Mapped[object] = mapped_column(String(100), comment="second_reviewer")
    second_review_date: Mapped[object] = mapped_column(DateTime, comment="second_review_date")
    second_review_opinion: Mapped[object] = mapped_column(Text, comment="second_review_opinion")
    audit_opinion: Mapped[object] = mapped_column(Text, comment="audit_opinion")
    workflow_status: Mapped[object] = mapped_column(String(40), comment="workflow_status")
    entered_by: Mapped[object] = mapped_column(String(100), comment="entered_by")
    entered_at: Mapped[object] = mapped_column(DateTime, comment="entered_at")
    reviewed_by: Mapped[object] = mapped_column(String(100), comment="reviewed_by")
    reviewed_at: Mapped[object] = mapped_column(DateTime, comment="reviewed_at")
    review_opinion: Mapped[object] = mapped_column(Text, comment="review_opinion")
    approved_by: Mapped[object] = mapped_column(String(100), comment="approved_by")
    approved_at: Mapped[object] = mapped_column(DateTime, comment="approved_at")
    approval_opinion: Mapped[object] = mapped_column(Text, comment="approval_opinion")
    cert_update_status: Mapped[object] = mapped_column(String(40), comment="cert_update_status")
    cert_update_id: Mapped[object] = mapped_column(BigInteger, comment="cert_update_id")
    cert_update_at: Mapped[object] = mapped_column(DateTime, comment="cert_update_at")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class FirstProductAudit(PkMixin):
    __tablename__ = "first_product_audit"
    name: Mapped[object] = mapped_column(String(400), comment="name")
    spec: Mapped[object] = mapped_column(String(400), comment="spec")
    factory: Mapped[object] = mapped_column(String(400), comment="factory")
    cls: Mapped[object] = mapped_column(String(40), comment="cls")
    reg_cert: Mapped[object] = mapped_column(String(200), comment="reg_cert")
    reg_cert_expire: Mapped[object] = mapped_column(String(40), comment="reg_cert_expire")
    license: Mapped[object] = mapped_column(String(200), comment="license")
    license_expire: Mapped[object] = mapped_column(String(40), comment="license_expire")
    func_desc: Mapped[object] = mapped_column(Text, comment="func_desc")
    comp_desc: Mapped[object] = mapped_column(Text, comment="comp_desc")
    applicant: Mapped[object] = mapped_column(String(100), comment="applicant")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    first_reviewer: Mapped[object] = mapped_column(String(100), comment="first_reviewer")
    first_review_date: Mapped[object] = mapped_column(DateTime, comment="first_review_date")
    first_review_opinion: Mapped[object] = mapped_column(Text, comment="first_review_opinion")
    second_reviewer: Mapped[object] = mapped_column(String(100), comment="second_reviewer")
    second_review_date: Mapped[object] = mapped_column(DateTime, comment="second_review_date")
    second_review_opinion: Mapped[object] = mapped_column(Text, comment="second_review_opinion")
    audit_opinion: Mapped[object] = mapped_column(Text, comment="audit_opinion")
    workflow_status: Mapped[object] = mapped_column(String(40), comment="workflow_status")
    entered_by: Mapped[object] = mapped_column(String(100), comment="entered_by")
    entered_at: Mapped[object] = mapped_column(DateTime, comment="entered_at")
    reviewed_by: Mapped[object] = mapped_column(String(100), comment="reviewed_by")
    reviewed_at: Mapped[object] = mapped_column(DateTime, comment="reviewed_at")
    review_opinion: Mapped[object] = mapped_column(Text, comment="review_opinion")
    approved_by: Mapped[object] = mapped_column(String(100), comment="approved_by")
    approved_at: Mapped[object] = mapped_column(DateTime, comment="approved_at")
    approval_opinion: Mapped[object] = mapped_column(Text, comment="approval_opinion")
    cert_update_status: Mapped[object] = mapped_column(String(40), comment="cert_update_status")
    cert_update_id: Mapped[object] = mapped_column(BigInteger, comment="cert_update_id")
    cert_update_at: Mapped[object] = mapped_column(DateTime, comment="cert_update_at")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class HealthCheckupPlan(PkMixin):
    __tablename__ = "health_checkup_plan"
    name: Mapped[object] = mapped_column(String(100), comment="name")
    dept: Mapped[object] = mapped_column(String(200), comment="dept")
    plan_year: Mapped[object] = mapped_column(String(20), comment="plan_year")
    plan_date: Mapped[object] = mapped_column(DateTime, comment="plan_date")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    checkup_items: Mapped[object] = mapped_column(Text, comment="checkup_items")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class HealthRecord(PkMixin):
    __tablename__ = "health_record"
    name: Mapped[object] = mapped_column(String(100), comment="name")
    dept: Mapped[object] = mapped_column(String(200), comment="dept")
    position: Mapped[object] = mapped_column(String(200), comment="position")
    health_cert_no: Mapped[object] = mapped_column(String(100), comment="health_cert_no")
    health_cert_org: Mapped[object] = mapped_column(String(200), comment="health_cert_org")
    health_cert_expire: Mapped[object] = mapped_column(String(40), comment="health_cert_expire")
    checkup_date: Mapped[object] = mapped_column(DateTime, comment="checkup_date")
    checkup_result: Mapped[object] = mapped_column(String(40), comment="checkup_result")
    work_restriction: Mapped[object] = mapped_column(String(100), comment="work_restriction")
    workflow_status: Mapped[object] = mapped_column(String(40), comment="workflow_status")
    entered_by: Mapped[object] = mapped_column(String(100), comment="entered_by")
    entered_at: Mapped[object] = mapped_column(DateTime, comment="entered_at")
    reviewed_by: Mapped[object] = mapped_column(String(100), comment="reviewed_by")
    reviewed_at: Mapped[object] = mapped_column(DateTime, comment="reviewed_at")
    review_opinion: Mapped[object] = mapped_column(Text, comment="review_opinion")
    approved_by: Mapped[object] = mapped_column(String(100), comment="approved_by")
    approved_at: Mapped[object] = mapped_column(DateTime, comment="approved_at")
    approval_opinion: Mapped[object] = mapped_column(Text, comment="approval_opinion")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class Inventory(PkMixin):
    __tablename__ = "inventory"
    udi: Mapped[object] = mapped_column(String(100), comment="udi")
    name: Mapped[object] = mapped_column(String(400), comment="name")
    spec: Mapped[object] = mapped_column(String(200), comment="spec")
    batch: Mapped[object] = mapped_column(String(200), comment="batch")
    qty: Mapped[object] = mapped_column(BigInteger, comment="qty")
    unit: Mapped[object] = mapped_column(String(40), comment="unit")
    min_stock: Mapped[object] = mapped_column(BigInteger, comment="min_stock")
    location: Mapped[object] = mapped_column(String(200), comment="location")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    ref_no: Mapped[object] = mapped_column(String(200), comment="ref_no")
    manufacturer: Mapped[object] = mapped_column(String(400), comment="manufacturer")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class InventoryLog(PkMixin):
    __tablename__ = "inventory_log"
    udi: Mapped[object] = mapped_column(String(100), comment="udi")
    name: Mapped[object] = mapped_column(String(400), comment="name")
    type: Mapped[object] = mapped_column(String(40), comment="type")
    change_qty: Mapped[object] = mapped_column(BigInteger, comment="change_qty")
    before_qty: Mapped[object] = mapped_column(BigInteger, comment="before_qty")
    after_qty: Mapped[object] = mapped_column(BigInteger, comment="after_qty")
    ref_no: Mapped[object] = mapped_column(String(100), comment="ref_no")
    operator: Mapped[object] = mapped_column(String(100), comment="operator")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    note: Mapped[object] = mapped_column(Text, comment="note")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class KnowledgeBase(PkMixin):
    __tablename__ = "knowledge_base"
    category: Mapped[object] = mapped_column(String(40), comment="category")
    code: Mapped[object] = mapped_column(String(60), comment="code")
    title: Mapped[object] = mapped_column(String(500), comment="title")
    gsp_ref: Mapped[object] = mapped_column(String(200), comment="gsp_ref")
    summary: Mapped[object] = mapped_column(String(500), comment="summary")
    content: Mapped[object] = mapped_column(Text, comment="content")
    steps: Mapped[object] = mapped_column(Text, comment="steps")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    tags: Mapped[object] = mapped_column(String(400), comment="tags")
    view_count: Mapped[object] = mapped_column(BigInteger, comment="view_count")
    sort_order: Mapped[object] = mapped_column(BigInteger, comment="sort_order")
    created_by: Mapped[object] = mapped_column(String(100), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    subcategory: Mapped[object] = mapped_column(String(100), comment="subcategory")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class MaintenancePlan(PkMixin):
    __tablename__ = "maintenance_plan"
    equip_name: Mapped[object] = mapped_column(String(400), comment="equip_name")
    equip_udi: Mapped[object] = mapped_column(String(100), comment="equip_udi")
    type: Mapped[object] = mapped_column(String(100), comment="type")
    plan_date: Mapped[object] = mapped_column(DateTime, comment="plan_date")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    person: Mapped[object] = mapped_column(String(100), comment="person")
    customer_name: Mapped[object] = mapped_column(String(200), comment="customer_name")
    dept_name: Mapped[object] = mapped_column(String(200), comment="dept_name")
    serial_no: Mapped[object] = mapped_column(String(200), comment="serial_no")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class NationalStandard(PkMixin):
    __tablename__ = "national_standard"
    std_no: Mapped[object] = mapped_column(String(100), comment="std_no")
    name: Mapped[object] = mapped_column(String(500), comment="name")
    type: Mapped[object] = mapped_column(String(40), comment="type")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    issue_date: Mapped[object] = mapped_column(DateTime, comment="issue_date")
    scope: Mapped[object] = mapped_column(Text, comment="scope")
    impl_date: Mapped[object] = mapped_column(DateTime, comment="impl_date")
    replace_std: Mapped[object] = mapped_column(String(500), comment="replace_std")
    summary: Mapped[object] = mapped_column(Text, comment="summary")
    compliance_req: Mapped[object] = mapped_column(Text, comment="compliance_req")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class OperationLog(PkMixin):
    __tablename__ = "operation_log"
    time: Mapped[object] = mapped_column(DateTime, comment="time")
    text: Mapped[object] = mapped_column(Text, comment="text")
    user: Mapped[object] = mapped_column(String(100), comment="user")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class OutboundRecord(PkMixin):
    __tablename__ = "outbound_record"
    order_no: Mapped[object] = mapped_column(String(100), comment="order_no")
    customer: Mapped[object] = mapped_column(String(400), comment="customer")
    customer_license: Mapped[object] = mapped_column(String(200), comment="customer_license")
    equip_name: Mapped[object] = mapped_column(String(400), comment="equip_name")
    equip_udi: Mapped[object] = mapped_column(String(100), comment="equip_udi")
    batch: Mapped[object] = mapped_column(String(100), comment="batch")
    reg_cert: Mapped[object] = mapped_column(String(200), comment="reg_cert")
    factory_name: Mapped[object] = mapped_column(String(200), comment="factory_name")
    prod_license_no: Mapped[object] = mapped_column(String(200), comment="prod_license_no")
    qty: Mapped[object] = mapped_column(BigInteger, comment="qty")
    unit: Mapped[object] = mapped_column(String(40), comment="unit")
    price: Mapped[object] = mapped_column(Float, comment="price")
    total: Mapped[object] = mapped_column(Float, comment="total")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    prod_date: Mapped[object] = mapped_column(DateTime, comment="prod_date")
    expire_date: Mapped[object] = mapped_column(DateTime, comment="expire_date")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    operator: Mapped[object] = mapped_column(String(100), comment="operator")
    reviewer: Mapped[object] = mapped_column(String(100), comment="reviewer")
    quality_approver: Mapped[object] = mapped_column(String(100), comment="quality_approver")
    recipient: Mapped[object] = mapped_column(String(100), comment="recipient")
    transport_condition: Mapped[object] = mapped_column(String(200), comment="transport_condition")
    storage_condition: Mapped[object] = mapped_column(String(200), comment="storage_condition")
    note: Mapped[object] = mapped_column(Text, comment="note")
    audit_trail: Mapped[object] = mapped_column(Text, comment="audit_trail")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class OutboundTemplate(PkMixin):
    __tablename__ = "outbound_template"
    name: Mapped[object] = mapped_column(String(200), comment="name")
    description: Mapped[object] = mapped_column(String(500), comment="description")
    config: Mapped[object] = mapped_column(Text, comment="config")
    is_default: Mapped[object] = mapped_column(SmallInteger, comment="is_default")
    created_by: Mapped[object] = mapped_column(String(100), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class Personnel(PkMixin):
    __tablename__ = "personnel"
    name: Mapped[object] = mapped_column(String(100), comment="name")
    dept: Mapped[object] = mapped_column(String(200), comment="dept")
    position: Mapped[object] = mapped_column(String(200), comment="position")
    role: Mapped[object] = mapped_column(String(200), comment="role")
    phone: Mapped[object] = mapped_column(String(60), comment="phone")
    cert: Mapped[object] = mapped_column(String(400), comment="cert")
    cert_no: Mapped[object] = mapped_column(String(200), comment="cert_no")
    cert_org: Mapped[object] = mapped_column(String(200), comment="cert_org")
    expire: Mapped[object] = mapped_column(String(40), comment="expire")
    train: Mapped[object] = mapped_column(String(200), comment="train")
    train_content: Mapped[object] = mapped_column(Text, comment="train_content")
    train_date: Mapped[object] = mapped_column(DateTime, comment="train_date")
    train_org: Mapped[object] = mapped_column(String(200), comment="train_org")
    train_result: Mapped[object] = mapped_column(String(40), comment="train_result")
    user_id: Mapped[object] = mapped_column(BigInteger, comment="user_id")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    workflow_status: Mapped[object] = mapped_column(String(40), comment="workflow_status")
    entered_by: Mapped[object] = mapped_column(String(100), comment="entered_by")
    entered_at: Mapped[object] = mapped_column(DateTime, comment="entered_at")
    reviewed_by: Mapped[object] = mapped_column(String(100), comment="reviewed_by")
    reviewed_at: Mapped[object] = mapped_column(DateTime, comment="reviewed_at")
    review_opinion: Mapped[object] = mapped_column(Text, comment="review_opinion")
    approved_by: Mapped[object] = mapped_column(String(100), comment="approved_by")
    approved_at: Mapped[object] = mapped_column(DateTime, comment="approved_at")
    approval_opinion: Mapped[object] = mapped_column(Text, comment="approval_opinion")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class ProcConsumable(PkMixin):
    __tablename__ = "proc_consumable"
    order_no: Mapped[object] = mapped_column(String(100), comment="order_no")
    supplier: Mapped[object] = mapped_column(String(200), comment="supplier")
    factory_name: Mapped[object] = mapped_column(String(200), comment="factory_name")
    equip_name: Mapped[object] = mapped_column(String(400), comment="equip_name")
    equip_model: Mapped[object] = mapped_column(String(200), comment="equip_model")
    qty: Mapped[object] = mapped_column(BigInteger, comment="qty")
    amount: Mapped[object] = mapped_column(Float, comment="amount")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    type: Mapped[object] = mapped_column(String(40), comment="type")
    batch: Mapped[object] = mapped_column(String(100), comment="batch")
    applicant: Mapped[object] = mapped_column(String(100), comment="applicant")
    acceptor: Mapped[object] = mapped_column(String(100), comment="acceptor")
    flow: Mapped[object] = mapped_column(String(200), comment="flow")
    prod_license_no: Mapped[object] = mapped_column(String(200), comment="prod_license_no")
    reg_cert_no: Mapped[object] = mapped_column(String(200), comment="reg_cert_no")
    auditor: Mapped[object] = mapped_column(String(100), comment="auditor")
    audit_date: Mapped[object] = mapped_column(DateTime, comment="audit_date")
    audit_opinion: Mapped[object] = mapped_column(Text, comment="audit_opinion")
    audit_status: Mapped[object] = mapped_column(String(40), comment="audit_status")
    linked_plan_id: Mapped[object] = mapped_column(BigInteger, comment="linked_plan_id")
    workflow_status: Mapped[object] = mapped_column(Text, comment="workflow_status")
    purchaser_accepted: Mapped[object] = mapped_column(Text, comment="purchaser_accepted")
    purchaser_accepted_at: Mapped[object] = mapped_column(DateTime, comment="purchaser_accepted_at")
    purchaser_opinion: Mapped[object] = mapped_column(Text, comment="purchaser_opinion")
    quality_reviewed: Mapped[object] = mapped_column(Text, comment="quality_reviewed")
    quality_reviewed_at: Mapped[object] = mapped_column(DateTime, comment="quality_reviewed_at")
    quality_review_opinion: Mapped[object] = mapped_column(Text, comment="quality_review_opinion")
    warehouse_confirmed: Mapped[object] = mapped_column(Text, comment="warehouse_confirmed")
    warehouse_confirmed_at: Mapped[object] = mapped_column(DateTime, comment="warehouse_confirmed_at")
    warehouse_opinion: Mapped[object] = mapped_column(Text, comment="warehouse_opinion")
    quality_approved: Mapped[object] = mapped_column(Text, comment="quality_approved")
    quality_approved_at: Mapped[object] = mapped_column(DateTime, comment="quality_approved_at")
    quality_approval_opinion: Mapped[object] = mapped_column(Text, comment="quality_approval_opinion")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class ProcEquipment(PkMixin):
    __tablename__ = "proc_equipment"
    order_no: Mapped[object] = mapped_column(String(100), comment="order_no")
    supplier: Mapped[object] = mapped_column(String(200), comment="supplier")
    factory_name: Mapped[object] = mapped_column(String(200), comment="factory_name")
    equip_name: Mapped[object] = mapped_column(String(400), comment="equip_name")
    equip_model: Mapped[object] = mapped_column(String(200), comment="equip_model")
    qty: Mapped[object] = mapped_column(BigInteger, comment="qty")
    amount: Mapped[object] = mapped_column(Float, comment="amount")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    type: Mapped[object] = mapped_column(String(40), comment="type")
    applicant: Mapped[object] = mapped_column(String(100), comment="applicant")
    acceptor: Mapped[object] = mapped_column(String(100), comment="acceptor")
    flow: Mapped[object] = mapped_column(String(200), comment="flow")
    prod_license_no: Mapped[object] = mapped_column(String(200), comment="prod_license_no")
    reg_cert_no: Mapped[object] = mapped_column(String(200), comment="reg_cert_no")
    auditor: Mapped[object] = mapped_column(String(100), comment="auditor")
    audit_date: Mapped[object] = mapped_column(DateTime, comment="audit_date")
    audit_opinion: Mapped[object] = mapped_column(Text, comment="audit_opinion")
    audit_status: Mapped[object] = mapped_column(String(40), comment="audit_status")
    linked_plan_id: Mapped[object] = mapped_column(BigInteger, comment="linked_plan_id")
    workflow_status: Mapped[object] = mapped_column(Text, comment="workflow_status")
    purchaser_accepted: Mapped[object] = mapped_column(Text, comment="purchaser_accepted")
    purchaser_accepted_at: Mapped[object] = mapped_column(DateTime, comment="purchaser_accepted_at")
    purchaser_opinion: Mapped[object] = mapped_column(Text, comment="purchaser_opinion")
    quality_reviewed: Mapped[object] = mapped_column(Text, comment="quality_reviewed")
    quality_reviewed_at: Mapped[object] = mapped_column(DateTime, comment="quality_reviewed_at")
    quality_review_opinion: Mapped[object] = mapped_column(Text, comment="quality_review_opinion")
    warehouse_confirmed: Mapped[object] = mapped_column(Text, comment="warehouse_confirmed")
    warehouse_confirmed_at: Mapped[object] = mapped_column(DateTime, comment="warehouse_confirmed_at")
    warehouse_opinion: Mapped[object] = mapped_column(Text, comment="warehouse_opinion")
    quality_approved: Mapped[object] = mapped_column(Text, comment="quality_approved")
    quality_approved_at: Mapped[object] = mapped_column(DateTime, comment="quality_approved_at")
    quality_approval_opinion: Mapped[object] = mapped_column(Text, comment="quality_approval_opinion")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class ProductAcceptance(PkMixin):
    __tablename__ = "product_acceptance"
    product_name: Mapped[object] = mapped_column(String(400), comment="product_name")
    product_udi: Mapped[object] = mapped_column(String(100), comment="product_udi")
    batch_no: Mapped[object] = mapped_column(String(100), comment="batch_no")
    manufacturer: Mapped[object] = mapped_column(String(200), comment="manufacturer")
    prod_license_no: Mapped[object] = mapped_column(String(200), comment="prod_license_no")
    reg_cert_no: Mapped[object] = mapped_column(String(200), comment="reg_cert_no")
    supplier: Mapped[object] = mapped_column(String(200), comment="supplier")
    quantity: Mapped[object] = mapped_column(BigInteger, comment="quantity")
    accept_date: Mapped[object] = mapped_column(DateTime, comment="accept_date")
    accept_person: Mapped[object] = mapped_column(String(100), comment="accept_person")
    check_type: Mapped[object] = mapped_column(String(60), comment="check_type")
    appearance_check: Mapped[object] = mapped_column(String(40), comment="appearance_check")
    quantity_check: Mapped[object] = mapped_column(String(40), comment="quantity_check")
    quality_check: Mapped[object] = mapped_column(String(40), comment="quality_check")
    overall_result: Mapped[object] = mapped_column(String(40), comment="overall_result")
    production_date: Mapped[object] = mapped_column(DateTime, comment="production_date")
    expiry_date: Mapped[object] = mapped_column(DateTime, comment="expiry_date")
    remark: Mapped[object] = mapped_column(Text, comment="remark")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    linked_proc_id: Mapped[object] = mapped_column(BigInteger, comment="linked_proc_id")
    workflow_status: Mapped[object] = mapped_column(String(40), comment="workflow_status")
    appearance_reviewer: Mapped[object] = mapped_column(String(100), comment="appearance_reviewer")
    appearance_date: Mapped[object] = mapped_column(DateTime, comment="appearance_date")
    appearance_remark: Mapped[object] = mapped_column(Text, comment="appearance_remark")
    quantity_reviewer: Mapped[object] = mapped_column(String(100), comment="quantity_reviewer")
    quantity_date: Mapped[object] = mapped_column(DateTime, comment="quantity_date")
    quantity_remark: Mapped[object] = mapped_column(Text, comment="quantity_remark")
    quality_reviewer: Mapped[object] = mapped_column(String(100), comment="quality_reviewer")
    quality_date: Mapped[object] = mapped_column(DateTime, comment="quality_date")
    quality_remark: Mapped[object] = mapped_column(Text, comment="quality_remark")
    final_approver: Mapped[object] = mapped_column(String(100), comment="final_approver")
    final_approval_date: Mapped[object] = mapped_column(DateTime, comment="final_approval_date")
    final_opinion: Mapped[object] = mapped_column(Text, comment="final_opinion")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class PurchasePlan(PkMixin):
    __tablename__ = "purchase_plan"
    plan_no: Mapped[object] = mapped_column(String(100), comment="plan_no")
    name: Mapped[object] = mapped_column(String(400), comment="name")
    spec_model: Mapped[object] = mapped_column(String(500), comment="spec_model")
    qty: Mapped[object] = mapped_column(BigInteger, comment="qty")
    budget: Mapped[object] = mapped_column(Float, comment="budget")
    category: Mapped[object] = mapped_column(String(40), comment="category")
    customer_name: Mapped[object] = mapped_column(String(200), comment="customer_name")
    factory_name: Mapped[object] = mapped_column(String(200), comment="factory_name")
    prod_license_no: Mapped[object] = mapped_column(String(200), comment="prod_license_no")
    reg_cert_no: Mapped[object] = mapped_column(String(200), comment="reg_cert_no")
    applicant: Mapped[object] = mapped_column(String(100), comment="applicant")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    date: Mapped[object] = mapped_column(String(40), comment="date")
    workflow_status: Mapped[object] = mapped_column(Text, comment="workflow_status")
    entered_by: Mapped[object] = mapped_column(Text, comment="entered_by")
    entered_at: Mapped[object] = mapped_column(DateTime, comment="entered_at")
    reviewed_by: Mapped[object] = mapped_column(Text, comment="reviewed_by")
    reviewed_at: Mapped[object] = mapped_column(DateTime, comment="reviewed_at")
    review_opinion: Mapped[object] = mapped_column(Text, comment="review_opinion")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class RecallRecord(PkMixin):
    __tablename__ = "recall_record"
    notify_no: Mapped[object] = mapped_column(String(100), comment="notify_no")
    product: Mapped[object] = mapped_column(String(400), comment="product")
    udi: Mapped[object] = mapped_column(String(100), comment="udi")
    batch: Mapped[object] = mapped_column(String(100), comment="batch")
    level: Mapped[object] = mapped_column(String(40), comment="level")
    reason: Mapped[object] = mapped_column(Text, comment="reason")
    source: Mapped[object] = mapped_column(String(200), comment="source")
    total_qty: Mapped[object] = mapped_column(BigInteger, comment="total_qty")
    recalled_qty: Mapped[object] = mapped_column(BigInteger, comment="recalled_qty")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    start_date: Mapped[object] = mapped_column(DateTime, comment="start_date")
    finish_date: Mapped[object] = mapped_column(DateTime, comment="finish_date")
    disposal_method: Mapped[object] = mapped_column(String(400), comment="disposal_method")
    report_no: Mapped[object] = mapped_column(String(100), comment="report_no")
    reporter: Mapped[object] = mapped_column(String(100), comment="reporter")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class RepairOrder(PkMixin):
    __tablename__ = "repair_order"
    equip_name: Mapped[object] = mapped_column(String(400), comment="equip_name")
    equip_udi: Mapped[object] = mapped_column(String(100), comment="equip_udi")
    desc: Mapped[object] = mapped_column(Text, comment="desc")
    reporter: Mapped[object] = mapped_column(String(100), comment="reporter")
    report_time: Mapped[object] = mapped_column(DateTime, comment="report_time")
    repairer: Mapped[object] = mapped_column(String(100), comment="repairer")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    cost: Mapped[object] = mapped_column(Float, comment="cost")
    customer_name: Mapped[object] = mapped_column(String(200), comment="customer_name")
    dept_name: Mapped[object] = mapped_column(String(200), comment="dept_name")
    serial_no: Mapped[object] = mapped_column(String(200), comment="serial_no")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class Roles(PkMixin):
    __tablename__ = "roles"
    code: Mapped[object] = mapped_column(String(100), comment="code")
    name: Mapped[object] = mapped_column(String(100), comment="name")
    description: Mapped[object] = mapped_column(Text, comment="description")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class StandardCheck(PkMixin):
    __tablename__ = "standard_check"
    equip_name: Mapped[object] = mapped_column(String(400), comment="equip_name")
    equip_udi: Mapped[object] = mapped_column(String(100), comment="equip_udi")
    std_no: Mapped[object] = mapped_column(String(100), comment="std_no")
    result: Mapped[object] = mapped_column(String(40), comment="result")
    check_date: Mapped[object] = mapped_column(DateTime, comment="check_date")
    std_name: Mapped[object] = mapped_column(String(500), comment="std_name")
    checker: Mapped[object] = mapped_column(String(100), comment="checker")
    check_method: Mapped[object] = mapped_column(String(400), comment="check_method")
    conclusion: Mapped[object] = mapped_column(Text, comment="conclusion")
    dept: Mapped[object] = mapped_column(String(200), comment="dept")
    rectify_measures: Mapped[object] = mapped_column(Text, comment="rectify_measures")
    rectify_deadline: Mapped[object] = mapped_column(String(40), comment="rectify_deadline")
    remark: Mapped[object] = mapped_column(Text, comment="remark")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class Supplier(PkMixin):
    __tablename__ = "supplier"
    name: Mapped[object] = mapped_column(String(400), comment="name")
    code: Mapped[object] = mapped_column(String(100), comment="code")
    type: Mapped[object] = mapped_column(String(100), comment="type")
    med_biz_license_no: Mapped[object] = mapped_column(String(200), comment="med_biz_license_no")
    license_expire: Mapped[object] = mapped_column(String(40), comment="license_expire")
    gsp_cert: Mapped[object] = mapped_column(String(200), comment="gsp_cert")
    scope: Mapped[object] = mapped_column(String(400), comment="scope")
    reg_capital: Mapped[object] = mapped_column(String(100), comment="reg_capital")
    address: Mapped[object] = mapped_column(String(500), comment="address")
    legal_person: Mapped[object] = mapped_column(String(100), comment="legal_person")
    contact: Mapped[object] = mapped_column(String(100), comment="contact")
    phone: Mapped[object] = mapped_column(String(60), comment="phone")
    email: Mapped[object] = mapped_column(String(200), comment="email")
    bank_info: Mapped[object] = mapped_column(String(400), comment="bank_info")
    rating: Mapped[object] = mapped_column(String(40), comment="rating")
    coop_since: Mapped[object] = mapped_column(String(20), comment="coop_since")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    review_status: Mapped[object] = mapped_column(String(40), comment="review_status")
    workflow_status: Mapped[object] = mapped_column(String(40), comment="workflow_status")
    entered_by: Mapped[object] = mapped_column(String(100), comment="entered_by")
    entered_at: Mapped[object] = mapped_column(DateTime, comment="entered_at")
    reviewed_by: Mapped[object] = mapped_column(String(100), comment="reviewed_by")
    reviewed_at: Mapped[object] = mapped_column(DateTime, comment="reviewed_at")
    review_opinion: Mapped[object] = mapped_column(Text, comment="review_opinion")
    approved_by: Mapped[object] = mapped_column(String(100), comment="approved_by")
    approved_at: Mapped[object] = mapped_column(DateTime, comment="approved_at")
    approval_opinion: Mapped[object] = mapped_column(Text, comment="approval_opinion")
    class2_filing_no: Mapped[object] = mapped_column(String(200), comment="class2_filing_no")
    auth_period: Mapped[object] = mapped_column(String(100), comment="auth_period")
    cert_update_status: Mapped[object] = mapped_column(String(40), comment="cert_update_status")
    cert_update_id: Mapped[object] = mapped_column(BigInteger, comment="cert_update_id")
    cert_update_at: Mapped[object] = mapped_column(DateTime, comment="cert_update_at")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class SupplierDoc(PkMixin):
    __tablename__ = "supplier_doc"
    supplier_id: Mapped[object] = mapped_column(BigInteger, comment="supplier_id")
    doc_type: Mapped[object] = mapped_column(String(100), comment="doc_type")
    title: Mapped[object] = mapped_column(String(400), comment="title")
    no: Mapped[object] = mapped_column(String(200), comment="no")
    issue_date: Mapped[object] = mapped_column(DateTime, comment="issue_date")
    expire_date: Mapped[object] = mapped_column(DateTime, comment="expire_date")
    file_type: Mapped[object] = mapped_column(String(40), comment="file_type")
    review_by: Mapped[object] = mapped_column(String(100), comment="review_by")
    review_date: Mapped[object] = mapped_column(DateTime, comment="review_date")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class SystemProfile(PkMixin):
    __tablename__ = "system_profile"
    name: Mapped[object] = mapped_column(String(400), comment="name")
    credit_code: Mapped[object] = mapped_column(String(100), comment="credit_code")
    enterprise_type: Mapped[object] = mapped_column(String(100), comment="enterprise_type")
    business_license: Mapped[object] = mapped_column(String(200), comment="business_license")
    business_license_expire: Mapped[object] = mapped_column(String(40), comment="business_license_expire")
    med_device_license: Mapped[object] = mapped_column(String(200), comment="med_device_license")
    med_device_license_expire: Mapped[object] = mapped_column(String(40), comment="med_device_license_expire")
    record_cert: Mapped[object] = mapped_column(String(200), comment="record_cert")
    record_cert_expire: Mapped[object] = mapped_column(String(40), comment="record_cert_expire")
    legal_person: Mapped[object] = mapped_column(String(100), comment="legal_person")
    enterprise_head: Mapped[object] = mapped_column(String(100), comment="enterprise_head")
    quality_manager: Mapped[object] = mapped_column(String(100), comment="quality_manager")
    quality_dept: Mapped[object] = mapped_column(String(200), comment="quality_dept")
    reg_address: Mapped[object] = mapped_column(String(500), comment="reg_address")
    warehouse_address: Mapped[object] = mapped_column(String(500), comment="warehouse_address")
    business_area: Mapped[object] = mapped_column(String(100), comment="business_area")
    warehouse_area: Mapped[object] = mapped_column(String(100), comment="warehouse_area")
    scope: Mapped[object] = mapped_column(Text, comment="scope")
    phone: Mapped[object] = mapped_column(String(60), comment="phone")
    email: Mapped[object] = mapped_column(String(200), comment="email")
    bank_name: Mapped[object] = mapped_column(String(200), comment="bank_name")
    bank_account: Mapped[object] = mapped_column(String(100), comment="bank_account")
    establish_date: Mapped[object] = mapped_column(DateTime, comment="establish_date")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    remark: Mapped[object] = mapped_column(Text, comment="remark")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    workflow_status: Mapped[object] = mapped_column(String(40), comment="workflow_status")
    entered_by: Mapped[object] = mapped_column(String(100), comment="entered_by")
    entered_at: Mapped[object] = mapped_column(DateTime, comment="entered_at")
    reviewed_by: Mapped[object] = mapped_column(String(100), comment="reviewed_by")
    reviewed_at: Mapped[object] = mapped_column(DateTime, comment="reviewed_at")
    review_opinion: Mapped[object] = mapped_column(Text, comment="review_opinion")
    approved_by: Mapped[object] = mapped_column(String(100), comment="approved_by")
    approved_at: Mapped[object] = mapped_column(DateTime, comment="approved_at")
    approval_opinion: Mapped[object] = mapped_column(Text, comment="approval_opinion")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class TempHumidityLog(PkMixin):
    __tablename__ = "temp_humidity_log"
    hour: Mapped[object] = mapped_column(String(20), comment="hour")
    temp: Mapped[object] = mapped_column(Float, comment="temp")
    humid: Mapped[object] = mapped_column(Float, comment="humid")
    record_date: Mapped[object] = mapped_column(DateTime, comment="record_date")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class TrainingPlan(PkMixin):
    __tablename__ = "training_plan"
    plan_no: Mapped[object] = mapped_column(String(60), comment="plan_no")
    title: Mapped[object] = mapped_column(String(400), comment="title")
    period_type: Mapped[object] = mapped_column(String(20), comment="period_type")
    period_label: Mapped[object] = mapped_column(String(100), comment="period_label")
    year: Mapped[object] = mapped_column(String(20), comment="year")
    content: Mapped[object] = mapped_column(Text, comment="content")
    target_audience: Mapped[object] = mapped_column(String(500), comment="target_audience")
    trainer: Mapped[object] = mapped_column(String(100), comment="trainer")
    location: Mapped[object] = mapped_column(String(400), comment="location")
    planned_date: Mapped[object] = mapped_column(DateTime, comment="planned_date")
    planned_hours: Mapped[object] = mapped_column(Float, comment="planned_hours")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    created_by: Mapped[object] = mapped_column(String(100), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    approved_by: Mapped[object] = mapped_column(String(100), comment="approved_by")
    approved_at: Mapped[object] = mapped_column(DateTime, comment="approved_at")
    approval_opinion: Mapped[object] = mapped_column(Text, comment="approval_opinion")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class TrainingRecord(PkMixin):
    __tablename__ = "training_record"
    record_no: Mapped[object] = mapped_column(String(60), comment="record_no")
    plan_id: Mapped[object] = mapped_column(BigInteger, comment="plan_id")
    plan_no: Mapped[object] = mapped_column(String(60), comment="plan_no")
    title: Mapped[object] = mapped_column(String(400), comment="title")
    training_type: Mapped[object] = mapped_column(String(60), comment="training_type")
    content: Mapped[object] = mapped_column(Text, comment="content")
    training_date: Mapped[object] = mapped_column(DateTime, comment="training_date")
    location: Mapped[object] = mapped_column(String(400), comment="location")
    trainer: Mapped[object] = mapped_column(String(100), comment="trainer")
    duration_hours: Mapped[object] = mapped_column(Float, comment="duration_hours")
    participants: Mapped[object] = mapped_column(Text, comment="participants")
    participant_count: Mapped[object] = mapped_column(BigInteger, comment="participant_count")
    assessment: Mapped[object] = mapped_column(String(40), comment="assessment")
    summary: Mapped[object] = mapped_column(Text, comment="summary")
    pdf_filename: Mapped[object] = mapped_column(String(500), comment="pdf_filename")
    pdf_path: Mapped[object] = mapped_column(String(500), comment="pdf_path")
    created_by: Mapped[object] = mapped_column(String(100), comment="created_by")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")

class Users(PkMixin):
    __tablename__ = "users"
    username: Mapped[object] = mapped_column(String(100), comment="username")
    password_hash: Mapped[object] = mapped_column(String(500), comment="password_hash")
    name: Mapped[object] = mapped_column(String(100), comment="name")
    dept: Mapped[object] = mapped_column(String(200), comment="dept")
    role_code: Mapped[object] = mapped_column(String(100), comment="role_code")
    phone: Mapped[object] = mapped_column(String(40), comment="phone")
    email: Mapped[object] = mapped_column(String(200), comment="email")
    status: Mapped[object] = mapped_column(String(40), comment="status")
    created_at: Mapped[object] = mapped_column(DateTime, comment="created_at")
    permission_overrides: Mapped[object] = mapped_column(Text, comment="permission_overrides")
    created_by: Mapped[object] = mapped_column(String(50), comment="created_by")
    updated_by: Mapped[object] = mapped_column(String(50), comment="updated_by")
    updated_at: Mapped[object] = mapped_column(DateTime, comment="updated_at")
    deleted: Mapped[object] = mapped_column(SmallInteger, comment="deleted")
