# -*- coding: utf-8 -*-
"""模块注册表：表名 -> (中文标题, 搜索字段, 图标名)  供前端菜单与CRUD路由生成"""
MODULES = [
    ("equip_ledger",        "设备台账",       ("name", "udi", "model", "factory")),
    ("inventory",           "库存管理",       ("name", "udi", "batch", "location")),
    ("inventory_log",       "库存流水",       ("name", "udi", "ref_no")),
    ("outbound_record",     "销售出库",       ("order_no", "customer", "equip_name")),
    ("expiry_warning",      "效期预警",       ("name", "batch")),
    ("purchase_plan",       "采购计划",       ("plan_no", "name", "applicant")),
    ("proc_equipment",      "设备采购单",     ("order_no", "equip_name", "supplier")),
    ("proc_consumable",     "耗材采购单",     ("order_no", "equip_name", "supplier")),
    ("product_acceptance",  "产品验收",       ("product_name", "batch_no", "supplier")),
    ("acceptance_record",   "验收记录",       ("equip_name", "person")),
    ("equip_inspection",    "设备巡检",       ("equip_name", "inspector")),
    ("equip_acceptance",    "设备验收",       ("equip_name", "person")),
    ("supplier",            "供应商档案",     ("name", "code", "contact")),
    ("supplier_doc",        "供应商资质文档", ("title", "doc_type")),
    ("customer_archive",    "客户档案",       ("name", "credit_code")),
    ("first_factory_audit", "首营企业审核",   ("name", "applicant")),
    ("first_product_audit", "首营产品审核",   ("name", "spec", "factory")),
    ("cert_update_request", "证照变更申请",   ("record_name", "module")),
    ("national_standard",   "国家标准库",     ("std_no", "name")),
    ("standard_check",      "标准符合性检查", ("equip_name", "std_no")),
    ("repair_order",        "维修工单",       ("equip_name", "reporter", "repairer")),
    ("maintenance_plan",    "保养计划",       ("equip_name", "type")),
    ("calibration_plan",    "计量计划",       ("equip_name", "cal_no")),
    ("calibration_record",  "计量记录",       ("equip_name", "cal_no", "org")),
    ("adverse_event",       "不良事件",       ("equip_name", "desc", "reporter")),
    ("recall_record",       "召回追溯",       ("notify_no", "product", "udi")),
    ("temp_humidity_log",   "温湿度记录",     ("hour", "record_date")),
    ("health_checkup_plan", "体检计划",       ("name", "dept")),
    ("health_record",       "健康档案",       ("name", "dept")),
    ("personnel",           "人员档案",       ("name", "dept", "position")),
    ("training_plan",       "培训计划",       ("plan_no", "title")),
    ("training_record",     "培训记录",       ("record_no", "title", "trainer")),
    ("knowledge_base",      "知识库/SOP",     ("title", "code", "tags")),
    ("finance_record",      "财务记录",       ("ref_no", "dept", "note")),
    ("operation_log",       "操作日志",       ("user", "text")),
    ("data_bridge_log",     "数据桥接日志",   ("bridge_type", "source_module")),
    ("approval_notification", "审批通知",     ("title", "module", "target_user")),
    ("outbound_template",   "出库模板",       ("name", "description")),
    ("system_profile",      "系统配置",       ("name")),
]
